### ISSUE TITLE
Problems running examples

### ISSUE THREAD

**Issue by unmau** [grundid/nfctools-examples#4]
Hi
First, thanks for all your work. 
Recently I bought ACR122U A9, and I was looking for any library to make an application which
communicate my usb reader with an android phone (Xperia S Jelly bean 4.1), I found this and I tried to run the examples, (Llcp service) but i get the following error, i didn't know well maven but I think its a problem about pom.xml, or at least netbeans says so.

Scanning for projects...

---
## Building NFC Tools examples 1.0-SNAPSHOT

The POM for org.nfctools:nfctools-core:jar:1.0-SNAPSHOT is missing, no dependency information available
## BUILD FAILURE

Total time: 1.792s
Finished at: Tue Oct 07 17:04:35 CDT 2014
## Final Memory: 5M/108M

Failed to execute goal on project nfctools-examples: Could not resolve dependencies for project org.nfctools:nfctools-examples:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.nfctools:nfctools-core:jar:1.0-SNAPSHOT, org.nfctools:nfctools-p2p:jar:1.0-SNAPSHOT: Could not find artifact org.nfctools:nfctools-core:jar:1.0-SNAPSHOT -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Is it anyway to not depend on maven? Could you help me please?

**Comment by grundid** [comment]
Have you tried the precompiled version of the nfctools-examples in the releases section above?

If you want to hack on the project you will need a dependency management tool like maven sooner or later so you might want to invest some time to get it running.

**Comment by leoexcellent** [comment]
I have this issue as well. If you fixed the issued, please replied me.
